services:
    api:
        build: .
        ports:
            - "8080:80"
            - "8443:443"
            - "5000:5000"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DefaultConnection=Server=db;Database=LoanSystemDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
        depends_on:
            - db
        networks:
            - loan-network

    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=YourStrong!Passw0rd
            - MSSQL_PID=Express
        ports:
            - "1433:1433"
        volumes:
            - sqldata:/var/opt/mssql
        networks:
            - loan-network

networks:
    loan-network:
        driver: bridge

volumes:
    sqldata:
